#!/usr/bin/env ruby
# frozen_string_literal: true

puts "~*" * 40
puts "TheRole: Welcome to the Development Container (Rails 3)"
system("docker compose -f dockerfiles/docker-compose.yml exec rails3 bash")
