#!/usr/bin/env ruby
# frozen_string_literal: true

puts "~*" * 40
puts "=> TheRole: Building Development environment"
puts

puts "=> Cloning TheRoleAPI gem"
system("git clone https://github.com/TheRole/the_role_api.git")
puts

puts "=> Cloning ToSlugParam gem"
system("git clone https://github.com/TheRole/to_slug_param.git")
puts
