#!/usr/bin/env ruby
# frozen_string_literal: true

puts "~*" * 40
puts "=> Building TheRole Development environment"
puts

puts "=> Cloning TheRoleAPI gem"
system("git clone git@github.com:TheRole/the_role_api.git")
puts

puts "=> Cloning ToSlugParam gem"
system("git clone git@github.com:TheOpenCMS/to_slug_param.git")
puts
