#!/usr/bin/env ruby
# frozen_string_literal: true

puts "~*" * 40
puts "TheRole: Running a container for development process"
system("docker compose -f dockerfiles/docker-compose.yml up --remove-orphans -d")
