#!/usr/bin/env ruby
# frozen_string_literal: true

puts "~*" * 40
puts "TheRole: Status of a container for development process"
system('docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Status}}" | grep the_role')
