#!/usr/bin/env ruby
# frozen_string_literal: true

# ==========================================================================================================
# RAILS 7. gem the_role_api
# ==========================================================================================================

puts '~*' * 40
puts '=> TESTING FOR RAILS 7'

rails_app = 'cd rails7-app'
install_gems = 'bundle install'
db_create = 'bundle exec rake db:create:all'
migrate_test_db = 'RAILS_ENV=test bundle exec rake db:migrate'
test_gem = 'RAILS_ENV=test bundle exec rspec ../the_role_specs/specs'

test_command = [rails_app, install_gems, db_create, migrate_test_db, test_gem].join(' && ')
command = "docker compose -f dockerfiles/docker-compose.yml exec rails bash -c " + "\"#{test_command}\""
puts command

system(command)
puts
