#!/usr/bin/env ruby
# frozen_string_literal: true

puts '~*' * 40
puts '=> Testing `to_slug_params` gem'
puts

rails_app = 'cd rails6-app'
install_gems = 'bundle install'
test_gem = 'RAILS_VERSION=6 RAILS_ENV=test bundle exec rspec ../to_slug_param/spec/helpers'

puts '=> TESTING FOR RAILS 6 APP'
system("#{rails_app} && #{install_gems} && #{test_gem}")
puts

rails_app = 'cd rails7-app'
install_gems = 'bundle install'
test_gem = 'RAILS_VERSION=7 RAILS_ENV=test bundle exec rspec ../to_slug_param/spec/helpers'

puts '=> TESTING FOR RAILS 7 APP'
system("#{rails_app} && #{install_gems} && #{test_gem}")
puts
