#!/usr/bin/env ruby
# frozen_string_literal: true

puts '~*' * 40
puts '=> Testing `to_slug_params` gem'
puts

# ==========================================================================================================
# RAILS 6. gem ToSlugParams
# ==========================================================================================================

puts '~*' * 40
puts '=> TESTING FOR RAILS 6 APP'

rails_app = 'cd rails6-app'
install_gems = 'bundle install'
migrate_test_db = 'RAILS_ENV=test bin/rails db:migrate'
test_gem = 'RAILS_VERSION=6 RAILS_ENV=test bundle exec rspec ../to_slug_param/spec/helpers'

test_rails6_command = [rails_app, install_gems, migrate_test_db, test_gem].join(' && ')
rails_6_command = "docker compose -f dockerfiles/docker-compose.yml exec rails bash -c " + "\"#{test_rails6_command}\""
puts rails_6_command

system(rails_6_command)
puts

# ==========================================================================================================
# RAILS 7. gem ToSlugParams
# ==========================================================================================================

puts '~*' * 40
puts '=> TESTING FOR RAILS 7 APP'

rails_app = 'cd rails7-app'
install_gems = 'bundle install'
migrate_test_db = 'RAILS_ENV=test bin/rails db:migrate'
test_gem = 'RAILS_VERSION=7 RAILS_ENV=test bundle exec rspec ../to_slug_param/spec/helpers'

test_rails7_command = [rails_app, install_gems, migrate_test_db, test_gem].join(' && ')
rails_7_command = "docker compose -f dockerfiles/docker-compose.yml exec rails bash -c " + "\"#{test_rails7_command}\""
puts rails_7_command

system(rails_7_command)
puts

# ==========================================================================================================
# Common information
# ==========================================================================================================

puts '~*' * 40
puts '=> Testing commands'
puts rails_6_command
puts
puts rails_7_command
