version: '3.9'

name: 'the_role_dev'

services:
  psql:
    image: postgres:15.1-bullseye
    user: root
    environment:
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../db/PGSQL:/var/lib/postgresql/data/pgdata

  rails3:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: ./dockerfiles/ruby-2.3.8+rails.Dockerfile
    working_dir: /home/the_role_dev
    command: 'tail -f /dev/null'
    volumes:
      - ../tmp:/home/the_role_dev/tmp
      - ../rails3-app:/home/the_role_dev/rails3-app
      - ../db/sqlite3:/home/the_role_dev/rails3-app/db/sqlite3
      - ../the_role_api:/home/the_role_dev/the_role_api
      - ../to_slug_param:/home/the_role_dev/to_slug_param
      - ../the_role_specs:/home/the_role_dev/the_role_specs

  rails:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: ./dockerfiles/ruby-2.7.8+rails.Dockerfile
    working_dir: /home/the_role_dev
    command: 'tail -f /dev/null'
    volumes:
      - ../tmp:/home/the_role_dev/tmp

      - ../rails6-app:/home/the_role_dev/rails6-app
      - ../db/sqlite3:/home/the_role_dev/rails6-app/db/sqlite3

      - ../rails7-app:/home/the_role_dev/rails7-app
      - ../db/sqlite3:/home/the_role_dev/rails7-app/db/sqlite3

      - ../the_role_api:/home/the_role_dev/the_role_api
      - ../to_slug_param:/home/the_role_dev/to_slug_param

      - ../the_role_specs:/home/the_role_dev/the_role_specs
    ports:
      - 3000:3000
    depends_on:
      - psql
